# Server configuration
server.port=8088

# Application name
spring.application.name=weather-app

# Thymeleaf configuration
spring.thymeleaf.cache=false
spring.thymeleaf.enabled=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

# Logging configuration
logging.level.com.apad.weather=INFO
logging.level.org.springframework.web=DEBUG